import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const shared = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { paddingHorizontal: 18, paddingBottom: 110, paddingTop: 8 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    padding: 16,
  },
  h1: { color: colors.text, fontSize: 24, fontWeight: "700" },
  h2: { color: colors.text, fontSize: 18, fontWeight: "700" },
  h3: { color: colors.text, fontSize: 15, fontWeight: "600" },
  num: { color: colors.text, fontWeight: "700" },
  label: { color: colors.dim, fontSize: 12.5 },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 14 },
  input: {
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 14,
    color: colors.text,
    fontSize: 14.5,
  },
  btn: {
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  btnPrimary: { backgroundColor: colors.accent },
  btnPrimaryText: { color: colors.accentInk, fontWeight: "700", fontSize: 14.5 },
  btnOutline: { backgroundColor: "transparent", borderWidth: 1, borderColor: colors.border },
  btnOutlineText: { color: colors.text, fontWeight: "700", fontSize: 14.5 },
  btnGhost: { backgroundColor: colors.surface2 },
  btnGhostText: { color: colors.text, fontWeight: "600", fontSize: 13 },
  pill: { paddingVertical: 5, paddingHorizontal: 10, borderRadius: 20 },
  pillOk: { backgroundColor: "rgba(143,227,154,0.14)" },
  pillOkText: { color: colors.ok, fontSize: 11.5, fontWeight: "600" },
  pillWarn: { backgroundColor: "rgba(255,122,69,0.14)" },
  pillWarnText: { color: colors.orange, fontSize: 11.5, fontWeight: "600" },
  checkbox: {
    width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, borderColor: colors.border,
    alignItems: "center", justifyContent: "center",
  },
  checkboxDone: { backgroundColor: colors.accent, borderColor: colors.accent },
  iconBtn: {
    width: 36, height: 36, borderRadius: 11, backgroundColor: colors.surface2,
    borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center",
  },
});
